spring:
  jdbc:
  h2:
    console:
      enabled: true
  datasource:
    generate-unique-name: false
    #    username: "postgres"
    #    password: "qwerty"
    url: "jdbc:h2:mem:testdb"
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    proporties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format-sql: true
    show-sql: true